### PR TITLE
Java upgrade

### PR DESCRIPTION
**Pull request by Leooo**
- [x] upgrade from Java 11 to Java 17

### CODE REVIEW

**Comment by Leooo** [comment]
@gavinmcnair let me PR something working in the next days instead (Java 11 upgrade is ready)

**Comment by gavinmcnair** [comment]
> @gavinmcnair let me PR something working in the next days instead (Java 11 upgrade is ready)

Sorry, i merged it. Create the PR against either version and i'll merge it anyway. Thanks

**Comment by Leooo** [comment]
if you revert the [last commit](https://github.com/gavinmcnair/kafka-connect-s3/pull/7/commits/700dcb3cfd1820ba213be3bf929ce672a963a7b5) then you should be good - although I also removed circleCI folder which maybe I shouldn't have ( I can't see tests running in PRs)

**Comment by gavinmcnair** [comment]
I've not used this in a while but i'll try and 

> > @gavinmcnair let me PR something working in the next days instead (Java 11 upgrade is ready)
> 
> Sorry, i merged it. Create the PR against either version and i'll merge it anyway. Thanks



> if you revert the [last commit](https://github.com/gavinmcnair/kafka-connect-s3/pull/7/commits/700dcb3cfd1820ba213be3bf929ce672a963a7b5) then you should be good - although I also removed circleCI folder which maybe I shouldn't have ( I can't see tests running in PRs)

I've added you as a collaborator so you should be able to do what you need to. I've not used this for about 5 years.

**Pull request merged**
